baseURL = 'https://jameslorencee.github.io/blogsbyjameslorencee'
languageCode = 'en-us'
title = 'Blogs by JamesLorence'
theme = 'archie'
copyright = "© JamesLorence"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/JamesLorencee"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/blogbyjameslorencee/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4